<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2mYsVNr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2mYsVNr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2mYsVNr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2mYsVNr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2mYsVNr\App_KernelDevDebugContainer([
    'container.build_hash' => '2mYsVNr',
    'container.build_id' => 'a745b3f9',
    'container.build_time' => 1584309623,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2mYsVNr');
